---
# This playbook woks for Fedora 37 and adds the a powerline prompt to bash
# Note that the home_dir var needs to be set to the user's home directory
# 
# Reference: https://fedoramagazine.org/tuning-your-bash-or-zsh-shell-in-workstation-and-silverblue/
# 
- name: Ensure Powerline is configured for Bash
  hosts: myhost

  vars:
    home_dir: "/home/serge"
  vars_files:
    - powerline_vars.yml

  tasks:
    - name: Ensure the pre-reqs are installed
      dnf:
        name: "{{ prereq_packages }}"
        state: present
      become: true

    - name: Ensure nerd fonts are downloaded using git
      git:
        repo: https://github.com/ryanoasis/nerd-fonts
        dest: "{{ home_dir }}/.nerd-fonts"
        depth: 1

    - name: Ensure nerd-fonts are installed
      shell: |
        cd {{ home_dir }}/.nerd-fonts
        ./install.sh
      become: true

    - name: Ensure the awesome fonts are installed
      dnf:
        name: "{{ font_packages }}"
        state: present
      become: true

    - name: Ensure that the Powerline packages are installed
      dnf:
        name: "{{ powerline_packages }}"
        state: present
      become: true

    - name: Ensure that the bashrc contains the powerline configuration block
      blockinfile:
        backup: true
        block: "{{ powerline_config }}"
        path: "{{ home_dir }}/.bashrc"
        state: present
